### PR TITLE
LRDOCS-10142 Update ja folder building-solutions-on-dxp for DXP

### PR DESCRIPTION
**Pull request by sophia6497**
Hi @holatuwol , 

    Minhchau, I failed script for `learn_translate_links.py` and `learn_header_ids.py` and when I build site locally, I run into: 
`sent 1,779,867,086 bytes  received 180,873 bytes  16,109,031.30 bytes/sec
total size is 1,778,537,211  speedup is 1.00
/liferay-learn-build/site /liferay-learn-build/site
The utility jq is not installed.
Starting server on port 7800...
./entrypoint.sh: line 39: cd: /liferay-learn-build/site/build/output: No such file or directory` 
So I am unable to check to see if there is any broken images or links or content. Can you please look into it? Thank you.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:close

**Comment by holatuwol** [comment]
Will review and re-send.

**Comment by holatuwol** [comment]
@sophia6497 

> I failed script for `learn_translate_links.py` and `learn_header_ids.py`

It looks like this batch of changes only updated titles, so the scripts didn't need to update anything.

> The utility jq is not installed

This happened due to some recent changes to `build_site.sh` in https://github.com/liferay/liferay-learn/commit/46e4e9d6ce420bc5c908741a6d2275e67b847a21 so the Docker container errored out early. I've updated the container to include jq, so you can pull the update, delete the existing container, and remake it.

I've squashed the changes and resent the pull request to https://github.com/liferay/liferay-learn/pull/197

**Comment by holatuwol** [comment]
Note to reviewers:

Please ignore this pull request in favor of https://github.com/liferay/liferay-learn/pull/198

**Comment by jrhoun** [comment]
See https://github.com/jrhoun/liferay-learn/pull/1415

**Pull request closed without merging**
