### PR TITLE
LCPE-838 update environment locations list

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LCPS-516

### CODE REVIEW

**Comment by ryannealeigh** [comment]
@zenorocha just added it!

**Comment by zenorocha** [comment]
That's fine by now.

**Comment by justinchoi001** [comment]
See https://github.com/jrhoun/liferay-learn/pull/108

**Comment by jrhoun** [comment]
Merged. Thank you.

**Comment by ryannealeigh** [comment]
Hi @jrhoun,

Should I send any future pulls directly to you?

**Comment by jrhoun** [comment]
Yes please @ryannealeigh .

**Pull request closed without merging**
