### PR TITLE
Use the correct environment variable

### PR DESCRIPTION
**Pull request by SGM3**
https://learn.liferay.com/dxp-cloud/latest/en/using-the-liferay-dxp-service/liferay-service-environment-variables.html
https://liferay.slack.com/archives/CKWDKQR9V/p1646923736529849

### CODE REVIEW

**Comment by jrhoun** [comment]
@Alec-Shay can you review this when able?

**Comment by Alec-Shay** [comment]
Hi @SGM3,

Thanks for catching this; this should have been updated at the same time it was in the other location, with an edit just like that. I may just make a minor change (moving the note so it doesn't interrupt what the other paragraph is saying), but otherwise it looks good to me. Thank you!

See: https://issues.liferay.com/browse/LRDOCS-10629

**Comment by Alec-Shay** [comment]
Forwarded here: https://github.com/jrhoun/liferay-learn/pull/1569

**Comment by jrhoun** [comment]
Rebased and pushed. e71e2f6c499ec6af16fe27037700d41a40d017d1

Thanks all!

**Pull request closed without merging**
