### PR TITLE
returnValue NOT return value

### PR DESCRIPTION
**Pull request by ethib137**
The variable returnValue not the return value determines the next task or state. It may also be helpful to include here that you need to set the value of returnValue to the "Transition ID" and possibly even show where it can be found.

### CODE REVIEW

**Comment by sez11a** [comment]
@rbohl Please review.

**Comment by rbohl** [comment]
Merged Locally.

**Comment by rbohl** [comment]
Forwarded in https://github.com/jrhoun/liferay-learn/pull/1551 and further work tracked in https://issues.liferay.com/browse/LRDOCS-10564
Feel free to close this.

**Comment by sez11a** [comment]
Superseded by https://github.com/jrhoun/liferay-learn/pull/1551; thank you @ethib137 !

**Pull request closed without merging**
